/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/ui/Login/Logo`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Login/Button`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Login/DiscordButton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Login/InputForm`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Login/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../components/ui/Login/Logo`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/Login/Button`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/Login/DiscordButton`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/Login/InputForm`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/Login/SignUp`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/../components/ui/Login/Logo${`?${string}` | `#${string}` | ''}` | `/../components/ui/Login/Button${`?${string}` | `#${string}` | ''}` | `/../components/ui/Login/DiscordButton${`?${string}` | `#${string}` | ''}` | `/../components/ui/Login/InputForm${`?${string}` | `#${string}` | ''}` | `/../components/ui/Login/SignUp${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/ui/Login/Logo`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Login/Button`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Login/DiscordButton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Login/InputForm`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Login/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
